### ISSUE TITLE
Map with directions

### ISSUE THREAD

**Issue by rzschoch** [fanningert/kirbycms-extension-gmaps#10]
A nice addition would be a map output with a directions link inside:
https://developers.google.com/maps/documentation/embed/start

Do you see a chance to implement map embeds that highlight a place or address with all the shown map features inside?

**Comment by fanningert** [comment]
It should be working with the place feature (highlight some places/Cities/Countries), but my current version has a bug in the place feature.

**Comment by fanningert** [comment]
Bad news . Currently is the ploygon feature for places not available via Google Maps Javascript API.

> This data is not available from the Google Maps APIs. An alternative solution would be to use KML data, which can probably be found online, and the URL can be retrieved. This can be imported into the map using the URL using google.maps.KmlLayer.
> - http://stackoverflow.com/questions/31701101/how-do-i-get-region-district-polygon-boundaries-data-from-google-maps

**Comment by rzschoch** [comment]
That’s sad. Does this also include specific addresses without a polygon highlighting a place? Like when you test this form with a more specific address (city + street): https://developers.google.com/maps/documentation/embed/start

**Comment by fanningert** [comment]
When I am searching for "Landstraße 3, 2000 Stockerau, Österreich", I get a map mith a marker.
This is possible in the current version.

_Example:_

```
(googlemaps zoom: 10)
  (marker place: Landstraße 3, 2000 Stockerau, Österreich)
(/googlemaps)
```

This is also working with `lat` and `lng`.

```
(googlemaps zoom: 10)
  (marker lat: 35.7152128 lng: 139.7981552)
(/googlemaps)
```

**Comment by fanningert** [comment]
To add extra controls, like "Direction link" or other functions is possible. But not default.
