### ISSUE TITLE
[Feature Request] Please Add Support for The Kirby CLI

### ISSUE THREAD

**Issue by luxlogica** [fanningert/kirbycms-extension-gmaps#15]
Please provide support for the official **[Kirby CLI](http://github.com/getkirby/cli)**, an amazing tool that allows power users to instal, update and manage kirby sites - and their plugins - through the command-line.

You can view the [official announcement](https://forum.getkirby.com/t/introducing-the-kirby-cli/) by Bastian on the Kirby Forum, [here](https://forum.getkirby.com/t/introducing-the-kirby-cli/).

**Comment by fanningert** [comment]
This is really a good idea. But in the moment I have no experience with PHP Composer. So I need some days for this.

**Comment by fanningert** [comment]
ok, it is working.

with `kirby plugin:install fanningert/kirbycms-extension-gmaps` you can install the plugin.
