### ISSUE TITLE
Question about the installation

### ISSUE THREAD

**Issue by janstieler** [fanningert/kirbycms-extension-gmaps#6]
Hi,
where I have to put the kirbycms-extension-gmaps-lib.php and the kirbycms-extension-gmaps.php in to use the plugin?

Kind regards,
Jan

**Comment by fanningert** [comment]
Hi Jan,
please read the README file. There is a install section.
https://github.com/fanningert/kirbycms-extension-gmaps#installation

But in short you can use git to install or manual copy the needed files in the right directories.
1. Create the directory `{kirby-install}/site/plugins/kirbycms-extension-gmaps/`
2. Copy the files `kirbycms-extension-gmaps-lib.php` and `kirbycms-extension-gmaps.php` into the created directory.
3. Copy the `gmaps.js` into the directory `{kirby-install}/assets/js/`
4. Add the needed entry in your snippets or template files. (https://github.com/fanningert/kirbycms-extension-gmaps#installation)
5. Set a height for the class `.googlemaps` Example: `.googlemaps { height: 300px }`

Much easy and better to update is to use `git`.
1. Go into the directory `{kirby-install}/site/plugins`
2. Execute the command `git clone https://github.com/fanningert/kirbycms-extension-gmaps.git`
3. Create a symbolic link for the javascript file. `ln -s {kirby-install}/site/plugins/kirbycms-extension-gmaps/assets/js/gmaps.js {kirby-install}/assets/js/gmaps.js` 
4. Add the needed entry in your snippets or template files. (https://github.com/fanningert/kirbycms-extension-gmaps#installation)
5. Set a height for the class `.googlemaps` Example: `.googlemaps { height: 300px }`
